[package]
name = "infix-to-rpn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xtree = { path = "C:\\Users\\fredd\\Desktop\\xtree-0.1.8\\" }