[package]
name = "rpn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
colored = "2.0.0"
derive_more = "0.99.17"
failure = "0.1.8"
ptree = "0.4.0"
r3bl_rs_utils = "0.9.6"
